services:
  app:
    build: .   # Replace with your Spring Boot Docker image
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/finomo_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: vinuthna
      SPRING_DATASOURCE_PASSWORD: vinuthna
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: vinuthna
      MYSQL_DATABASE: finomo_db
      MYSQL_USER: vinuthna
      MYSQL_PASSWORD: vinuthna
      MYSQL_ROOT_HOST: "%"
      MYSQL_DEFAULT_AUTH: mysql_native_password
    ports:
      - "3306:3306"
